import { DownloadOutlined, EllipsisOutlined, FileOutlined, FolderAddOutlined, FolderFilled, UploadOutlined } from '@ant-design/icons';
import { Button, Dropdown, Empty, Input, Modal, Space, Upload, message } from 'antd';
import { createStyles } from 'antd-style';
import { useCallback, useEffect, useState } from 'react';
import { WhiteNarrowBlock } from '~/styles/common/Block.styles';
import { PageHeader } from '~/components/common/PageHeader/PageHeader';
import { createDriveFolder, downloadDriveFile, listDriveItems, uploadDriveFile } from '~/lib/api/drive';
import { media } from '~/styles/responsive';

type Item = { id: number; type: 'FOLDER' | 'FILE'; name: string; size?: number; ownerLoginId: string; updatedAt: string };
const useStyles = createStyles(({ css }) => ({
  table: css`width:100%;overflow:hidden;border:1px solid #e8e2da;border-radius:12px;`,
  header: css`display:grid;grid-template-columns:minmax(0,1.8fr) minmax(130px,.7fr) minmax(120px,.55fr) 110px 48px;align-items:center;min-height:56px;padding:0 18px;background:#eef5f3;color:#513b28;font-weight:700;${media.mobile}{grid-template-columns:minmax(0,1fr) 42px;.meta{display:none;}}`,
  row: css`display:grid;grid-template-columns:minmax(0,1.8fr) minmax(130px,.7fr) minmax(120px,.55fr) 110px 48px;align-items:center;min-height:72px;padding:0 18px;border-top:1px solid #eee9e3;&:hover{background:#e7f3ef;}${media.mobile}{grid-template-columns:minmax(0,1fr) 42px;min-height:64px;.meta{display:none;}}`,
  name: css`display:flex;min-width:0;align-items:center;gap:14px;color:#3f2e20;font-size:1rem;font-weight:650;> :last-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}`,
  folder: css`font-size:25px;color:#f4c65a;`, file: css`font-size:23px;color:#48b99a;`, muted: css`color:#81766c;`, owner: css`overflow:hidden;color:#65584d;text-overflow:ellipsis;white-space:nowrap;`,
}));
const size = (value?:number) => !value ? '—' : value < 1048576 ? `${Math.ceil(value / 1024)}KB` : `${(value / 1048576).toFixed(1)}MB`;
const date = (value:string) => new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric'}).format(new Date(value));
export default function DrivePage(){const {styles}=useStyles();const [items,setItems]=useState<Item[]>([]);const [parentId,setParentId]=useState<number>();const [name,setName]=useState('');const [open,setOpen]=useState(false);const load=useCallback(async()=>setItems((await listDriveItems(parentId)).data),[parentId]);useEffect(()=>{load();},[load]);const folder=async()=>{await createDriveFolder(name,parentId);setName('');setOpen(false);load();};const upload=async(file:File)=>{await uploadDriveFile(file,parentId);message.success('파일을 업로드했습니다.');load();return false;};const download=async(item:Item)=>{const {data}=await downloadDriveFile(item.id);const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download=item.name;a.click();URL.revokeObjectURL(url);};const openItem=(item:Item)=>item.type==='FOLDER'?setParentId(item.id):download(item);return <WhiteNarrowBlock><PageHeader title="파일 관리" actions={<Space><Button onClick={()=>setParentId(undefined)}>내 파일</Button><Button icon={<FolderAddOutlined/>} onClick={()=>setOpen(true)}>폴더 만들기</Button><Upload showUploadList={false} beforeUpload={upload}><Button type="primary" icon={<UploadOutlined/>}>업로드</Button></Upload></Space>}/>{items.length===0?<Empty description="이 폴더는 비어 있습니다."/>:<div className={styles.table}><div className={styles.header}><span>이름</span><span className="meta">소유자</span><span className="meta">수정 날짜</span><span className="meta">파일 크기</span><span/></div>{items.map(item=><div className={styles.row} key={item.id} role="button" tabIndex={0} onClick={()=>openItem(item)} onKeyDown={event=>event.key==='Enter'&&openItem(item)}><div className={styles.name}>{item.type==='FOLDER'?<FolderFilled className={styles.folder}/>:<FileOutlined className={styles.file}/>}<span>{item.name}</span></div><span className={`${styles.owner} meta`}>{item.ownerLoginId}</span><span className={`${styles.muted} meta`}>{date(item.updatedAt)}</span><span className={`${styles.muted} meta`}>{size(item.size)}</span><Dropdown trigger={['click']} menu={{items:item.type==='FILE'?[{key:'d',label:'다운로드',icon:<DownloadOutlined/>,onClick:()=>download(item)}]:[]}}><Button type="text" aria-label={`${item.name} 메뉴`} icon={<EllipsisOutlined/>} onClick={event=>event.stopPropagation()}/></Dropdown></div>)}</div>}<Modal title="새 폴더" open={open} onOk={folder} onCancel={()=>setOpen(false)}><Input autoFocus value={name} onChange={event=>setName(event.target.value)} onPressEnter={folder} placeholder="폴더 이름"/></Modal></WhiteNarrowBlock>}
